# Generated by Django 5.1.5 on 2025-03-23 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0002_alter_users_email_alter_users_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
    ]
