# Generated by Django 5.1.5 on 2025-03-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0003_rename_products_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
