# Generated by Django 5.1.5 on 2025-03-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender_category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], max_length=10)),
                ('category', models.CharField(choices=[('Ring', 'Ring'), ('Necklace', 'Necklace'), ('Earring', 'Earring'), ('Bracelet', 'Bracelet')], max_length=20)),
                ('color', models.CharField(choices=[('#FFD700', 'Gold'), ('#C0C0C0', 'Silver'), ('#B76E79', 'Rose Gold'), ('#D4AF37', 'Antique Gold'), ('#8A7967', 'Bronze'), ('#E5E4E2', 'Platinum'), ('#AA6C39', 'Copper'), ('#E0115F', 'Ruby Red'), ('#7CFC00', 'Emerald Green'), ('#1E90FF', 'Sapphire Blue'), ('#9932CC', 'Amethyst Purple'), ('#FF1493', 'Pink Diamond'), ('#FFFFFF', 'Pearl White'), ('#000000', 'Onyx Black')], max_length=7)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
