# Generated by Django 5.1.5 on 2025-03-25 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0006_alter_product_image_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justdil.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justdil.users')),
            ],
        ),
    ]
