# Generated by Django 5.1.5 on 2025-03-25 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0007_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='N_Users',
        ),
    ]
