# Generated by Django 5.1.5 on 2025-03-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0008_rename_users_n_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='n_users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='n_users',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='n_users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='n_users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
