# Generated by Django 5.1.5 on 2025-04-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0012_alter_order_user_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
