# Generated by Django 5.1.5 on 2025-04-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0017_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_gallery/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='justdil.newproduct')),
            ],
        ),
    ]
