# Generated by Django 5.1.5 on 2025-04-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0018_newproductimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
