# Generated by Django 5.1.5 on 2025-04-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0022_remove_newproduct_color_remove_product_color_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproduct',
            name='color',
            field=models.CharField(choices=[('#FFD700', 'Gold'), ('#C0C0C0', 'Silver'), ('#B76E79', 'Rose Gold'), ('#D4AF37', 'Antique Gold'), ('#8A7967', 'Bronze'), ('#E5E4E2', 'Platinum'), ('#AA6C39', 'Copper'), ('#E0115F', 'Ruby Red'), ('#7CFC00', 'Emerald Green'), ('#1E90FF', 'Sapphire Blue'), ('#9932CC', 'Amethyst Purple'), ('#FF1493', 'Pink Diamond'), ('#FFFFFF', 'Pearl White'), ('#000000', 'Onyx Black')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('#FFD700', 'Gold'), ('#C0C0C0', 'Silver'), ('#B76E79', 'Rose Gold'), ('#D4AF37', 'Antique Gold'), ('#8A7967', 'Bronze'), ('#E5E4E2', 'Platinum'), ('#AA6C39', 'Copper'), ('#E0115F', 'Ruby Red'), ('#7CFC00', 'Emerald Green'), ('#1E90FF', 'Sapphire Blue'), ('#9932CC', 'Amethyst Purple'), ('#FF1493', 'Pink Diamond'), ('#FFFFFF', 'Pearl White'), ('#000000', 'Onyx Black')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
