# Generated by Django 5.1.5 on 2025-04-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0025_orderitem_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_number',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
