# Generated by Django 5.1.5 on 2025-04-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0026_remove_orderitem_order_number_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='justdil.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='best_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='justdil.bestproduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='new_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='justdil.newproduct'),
        ),
    ]
