# Generated by Django 5.1.5 on 2025-04-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0027_remove_order_created_at_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
