# Generated by Django 5.1.5 on 2025-05-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0033_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
