# Generated by Django 5.1.5 on 2025-05-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0036_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_applied',
            field=models.BooleanField(default=False),
        ),
    ]
