# Generated by Django 5.1.5 on 2025-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0037_cart_coupon_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='m_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
