# Generated by Django 5.1.5 on 2025-05-20 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('justdil', '0039_cart_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestproduct',
            name='category',
            field=models.CharField(choices=[('Ring', 'Ring'), ('Necklace', 'Necklace'), ('Earring', 'Earring'), ('Bracelet', 'Bracelet'), ('Jewelry_Set', 'Jewelry_Set'), ('Jewellery', 'Jewellery'), ('Hair_Accessories', 'Hair_Accessories'), ('Toys', 'Toys'), ('Bags&More', 'Bags&More')], max_length=20),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='category',
            field=models.CharField(choices=[('Ring', 'Ring'), ('Necklace', 'Necklace'), ('Earring', 'Earring'), ('Bracelet', 'Bracelet'), ('Jewelry_Set', 'Jewelry_Set'), ('Jewellery', 'Jewellery'), ('Hair_Accessories', 'Hair_Accessories'), ('Toys', 'Toys'), ('Bags&More', 'Bags&More')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ring', 'Ring'), ('Necklace', 'Necklace'), ('Earring', 'Earring'), ('Bracelet', 'Bracelet'), ('Jewelry_Set', 'Jewelry_Set'), ('Jewellery', 'Jewellery'), ('Hair_Accessories', 'Hair_Accessories'), ('Toys', 'Toys'), ('Bags&More', 'Bags&More')], max_length=20),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
