# Generated by Django 5.1.5 on 2025-06-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0041_bestproduct_discount_bestproduct_j_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestproduct',
            name='discount',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='newproduct',
            name='discount',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
