# Generated by Django 5.1.5 on 2025-06-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0044_remove_product_color_productcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='color_code',
        ),
    ]
