# Generated by Django 5.1.5 on 2025-06-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0046_categorytag_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
