# Generated by Django 5.1.5 on 2025-06-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdil', '0048_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible_when_out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
